<a href="https://colab.research.google.com/github/atebah/Viewers/blob/master/VIDA_MONAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# installations


In [ ]:
!sudo apt-get update -y
!sudo apt-get install python3.11


Hit:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [8,788 kB]
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:11 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [3,965 kB]
Get:13 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install gdcm
!pip install pylibjpeg pylibjpeg-libjpeg


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 33.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 55.3 MB/s eta 0:00:00


In [ ]:
!pip install highdicom

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 24.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 92.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 100.8 MB/s eta 0:00:00


In [ ]:
!pip install monai-deploy-app-sdk

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.6/132.6 kB 9.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.1/41.1 MB 25.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 62.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.5/287.5 kB 19.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.4/115.4 kB 10.5 MB/s eta 0:00:00
  Attempting uninstall: psutil
    Found existing installation: psutil 5.9.5
    Uninstalling psutil-5.9.5:
      Successfully uninstalled psutil-5.9.5
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyjpegls 1.5.1 requires numpy>=2.0, but you h

In [ ]:
!pip install monai

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 26.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 38.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 25.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 37.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 86.5 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling 

In [ ]:
!git clone https://github.com/roeez/CalcificationDetection.git

Cloning into 'CalcificationDetection'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 11 (delta 1), reused 0 (delta 0), pack-reused 7 (from 1)
Receiving objects: 100% (11/11), 6.90 MiB | 10.76 MiB/s, done.
Resolving deltas: 100% (1/1), done.


In [ ]:
!rm -rf dcm

In [ ]:
!mkdir dcm input

In [ ]:
%env HOLOSCAN_INPUT_PATH input
%env HOLOSCAN_MODEL_PATH /content/models/model/model.ts
%env HOLOSCAN_OUTPUT_PATH output

env: HOLOSCAN_INPUT_PATH=input
env: HOLOSCAN_MODEL_PATH=/content/models/model/model.ts
env: HOLOSCAN_OUTPUT_PATH=output


In [ ]:
import shutil
import glob
dcm_path = glob.glob("/content/drive/MyDrive/vida/DICOM_data/*")
for dcm in dcm_path:
  shutil.copy(dcm,"/content/input")

# convert model.pth to torchscript model.ts

In [ ]:
# !mkdir "/content/output" "/content/output/saved_images_folder" "/content/model"
!mkdir "/content/models" "/content/models/model"

In [ ]:
import torch
from torch import nn

class CBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(CBlock, self).__init__()
        assert out_channels % 4 == 0
        self.conv3 = nn.Conv2d(in_channels, out_channels//4, 3, padding=3//2)
        self.conv5 = nn.Conv2d(in_channels, out_channels//4, 5, padding=5//2)
        self.conv7 = nn.Conv2d(in_channels, out_channels//4, 7, padding=7//2)
        self.conv9 = nn.Conv2d(in_channels, out_channels//4, 9, padding=9//2)
        self.bn = nn.BatchNorm2d(out_channels)
        self.act = nn.ReLU()

    def forward(self, x):
        return self.act(self.bn(torch.cat([self.conv3(x), self.conv5(x), self.conv7(x), self.conv9(x)], 1)))

class NetC(nn.Module):
    def __init__(self, tag, kernel_size=9, skip_connections=True, batch_norm=True, kernel_depth_seed=4, network_depth=4, act_func=nn.ReLU(),
                 initializer=None):
        super(NetC, self).__init__()
        self.tag = tag
        self.block1 = CBlock(1, 4)
        self.block2 = CBlock(4, 16)
        self.block3 = CBlock(16, 32)
        self.block4 = CBlock(32, 64)
        self.block5 = CBlock(64, 128)
        self.pred = nn.Conv2d(128, 1, 5, padding=5//2)

    def forward(self, x):
        x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)
        x = self.block4(x)
        x = self.block5(x)
        return self.pred(x)

model = NetC(tag='encoder')
if torch.cuda.is_available():
  model.load_state_dict(torch.load("/content/CalcificationDetection/C__00900.weights"))
else:
  model.load_state_dict(torch.load("/content/CalcificationDetection/C__00900.weights",map_location=torch.device('cpu')))
model.eval()
# Create dummy input (match your model input shape)
dummy_input = torch.randn(1, 1, 224, 224)  # Modify based on your model

# Convert to TorchScript using tracing
traced_model = torch.jit.trace(model, dummy_input)

# Save the model
traced_model.save("/content/models/model/model.ts")

# Operator

In [ ]:
# for classifer
import json
import logging
import os
from pathlib import Path
from typing import Dict, Optional

import torch

from monai.data import DataLoader, Dataset
from monai.deploy.core import AppContext, ConditionType, Fragment, Image, Operator, OperatorSpec
from monai.deploy.operators.monai_seg_inference_operator import InMemImageReader
from monai.transforms import (
    Activations,
    Compose,
    EnsureChannelFirst,
    EnsureType,
    LoadImage,
    NormalizeIntensity,
    RepeatChannel,
    Resize,
    SqueezeDim,
)

In [ ]:
# for segmentation model
from monai.deploy.core import AppContext, ConditionType, Fragment, Operator, OperatorSpec
from monai.deploy.operators.monai_seg_inference_operator import InfererType, InMemImageReader, MonaiSegInferenceOperator
from monai.transforms import (
    Activationsd,
    AsDiscreted,
    Compose,
    CropForegroundd,
    EnsureChannelFirstd,
    Invertd,
    LoadImaged,
    ScaleIntensityRanged,
    Spacingd,
)

In [ ]:
import numpy as np
import cv2

## VIDAReadDcmOperator

In [ ]:
!mkdir DCM2PNG

mkdir: cannot create directory ‘DCM2PNG’: File exists


In [ ]:
class VIDAReadDcmOperator (Operator):
    DEFAULT_INPUT_FOLDER = Path.cwd() / "input"
    DEFAULT_OUTPUT_NAME = "image"  ## ===> saving output dcm2png to an in-memmory object
    DCM2PNG_OUTPUT_FOLDER = Path.cwd() / "DCM2PNG"
    def __init__(
        self,
        fragment: Fragment,
        *args,
        input_folder: Path = DEFAULT_INPUT_FOLDER,
        output_name: str = DEFAULT_OUTPUT_NAME,
        **kwargs,
    ):
      self._logger = logging.getLogger("{}.{}".format(__name__, type(self).__name__))
      self.input_path = input_folder
      self.index = 0
      self.output_name_image = (
          output_name.strip() if output_name and len(output_name.strip()) > 0 else VIDAReadDcmOperator.DEFAULT_OUTPUT_NAME
      )
      self.output_folder = VIDAReadDcmOperator.DCM2PNG_OUTPUT_FOLDER
      self.output_folder.mkdir(parents=True, exist_ok=True)


      super().__init__(fragment, *args, **kwargs)

    def setup(self, spec: OperatorSpec):
        """Set up the named input and output port(s)"""
        spec.output(self.output_name_image)

    def left_mamm(self,mamm):
      if mamm[:, :200, ...].sum() < mamm[:, -200:, ...].sum():
          mamm[:, :, ...] = mamm[:, ::-1, ...]
          print("#### left mamm ####")
      return mamm

    def cut_mamm(self,mamm, act_w):
      h = mamm.shape[0]
      mamm = mamm[:h, :act_w]
      print("#### cut mamm ####",mamm.shape)
      return mamm

    def get_act_width(self,mamm):
      w = mamm.shape[1] // 3
      while mamm[:, w:].max() > 0:
          w += 1
      print("#### get_act_width ####")
      return w

    def clean_mamm(self,mamm):
      background_val = 0
      mamm[:10, :, ...] = 0
      mamm[-10:, :, ...] = 0
      mamm[:, -10:, ...] = 0
      msk1 = (mamm[:, :, 0] == mamm[:, :, 1]) & (mamm[:, :, 1] == mamm[:, :, 2])
      mamm = mamm.mean(axis=2) * msk1
      msk = np.uint8((mamm > background_val) * 255)
      msk = cv2.morphologyEx(msk, cv2.MORPH_CLOSE, cv2.getStructuringElement(cv2.MORPH_RECT, (50, 50)))
      comps = cv2.connectedComponentsWithStats(msk)
      common_label = np.argmax(comps[2][1:, cv2.CC_STAT_AREA]) + 1
      msk = (comps[1] == common_label).astype(np.uint8)
      mamm[:, :] = msk * mamm[:, :]
      print("#### clean mamm ####")
      return mamm

    def mamms_preprocess(self,mamm):
      print("#### preprocess mamm ####")
      mamm = self.left_mamm(mamm)
      mamm = self.clean_mamm(mamm)
      act_w = self.get_act_width(mamm)
      mamm = self.cut_mamm(mamm, act_w)
      return mamm

    def load_mamm(self,mamm, max_height=0, width=0, encoder=None):
      print("#### load mamm ####")
      # mamm = cv2.imread(case_path).astype(np.float32) / 255
      mamm = mamm.astype(np.float32) / 255
      mamm = self.mamms_preprocess(mamm)
      return mamm, mamm.shape[1]


    def compute(self, op_input, op_output, context):
        import numpy as np
        import pydicom
        import cv2
        from torchvision.transforms import ToPILImage
        print("#######  converting DICOM to numpy array  #######")

        # Input path is stored in the object attribute, but could change to use a named port if need be.
        input_path = self.input_path
        if input_path.is_dir():
            # input_path = next(self.input_path.glob("*.*"))  # take the first file
            input_path = os.path.join("/content/input",os.listdir(input_path)[0])

        print(f" the input path is {input_path}")

        ds = pydicom.dcmread(input_path)
        image_array = ds.pixel_array
        if len(image_array.shape) == 2:
          image_array = cv2.cvtColor(image_array, cv2.COLOR_GRAY2RGB)

        print("image shape before preprocess: ", image_array.shape)
        ####################  load_mamm  #######################
        image_preprocessed, sh = self.load_mamm(image_array)
        ########################################################
        print("#######  DICOM converted  ########\n",image_preprocessed)
        norm_img = cv2.normalize(image_preprocessed,None,0,255,cv2.NORM_MINMAX, cv2.CV_8U)
        cv2.imwrite("/content/DCM2PNG/dcm2pmg.png",norm_img)
        # to_pil = ToPILImage()
        # pil_image = to_pil(image_preprocessed)
        # output_image = Image(image_arr)  # create Image domain object with a numpy array
        op_output.emit(image_preprocessed, self.output_name_image)  # cannot omit the name even if single output.



## VIDAoperator

In [ ]:
class VIDAoperator(Operator):
  DEFAULT_OUTPUT_FOLDER = Path.cwd() / "output/saved_images_folder"
  MODEL_LOCAL_PATH = Path(os.environ.get("HOLOSCAN_MODEL_PATH", Path.cwd() / "model/model.ts"))


  def __init__(
        self,
        fragment: Fragment,
        *args,
        app_context: AppContext,
        model_name: Optional[str] = "",
        model_path: Path = MODEL_LOCAL_PATH,
        output_folder: Path = DEFAULT_OUTPUT_FOLDER,
        **kwargs,
    ):
        # the names used for the model inference input and output
        self._input_dataset_key = "image"
        self._pred_dataset_key = "pred"

        self.model_path = model_path
        self.output_folder = output_folder
        self.output_folder.mkdir(parents=True, exist_ok=True)
        self.app_context = app_context
        self.input_name_image = "image"
        self.output_name_seg = "seg_image"
        self.output_name_saved_images_folder = "saved_images_folder"

        # Need the path to load the models when they are not loaded in the execution context
        self.tsmodel,self.ptmodel = self._get_model(self.app_context, self.model_path)

        # The base class has an attribute called fragment to hold the reference to the fragment object
        super().__init__(fragment, *args, **kwargs)

  def setup(self, spec: OperatorSpec):
        spec.input(self.input_name_image)
        spec.output(self.output_name_seg)
        spec.output(self.output_name_saved_images_folder).condition(ConditionType.NONE)


  def _get_model(self, app_context: AppContext, model_path: Path):
      """Load the model from context or file and set the predictor function."""
      print("======  getting the model  =======")
      from CalcificationDetection.core import NetC
      pt_model = NetC(tag='encoder')
      pt_model.eval()

      # Load the PyTorch model
      ts_model = torch.jit.load(
          "/content/models/model/model.ts",
          map_location=torch.device("cuda" if torch.cuda.is_available() else "cpu"),
      )

      pt_model.load_state_dict(torch.load('/content/CalcificationDetection/C__00900.weights',
                                                         map_location=next(model.parameters()).device, weights_only=True))


      return ts_model,pt_model

  def compute(self, op_input, op_output, context:AppContext):

      import torch
      import numpy as np
      from torchvision.transforms import ToPILImage
      import cv2
      from CalcificationDetection.core import predict

      print("===== Passing image to the model =====")


      # Receive the image object (assuming it's in monai.deploy.core.domain.image.Image format)
      numpy_image: Image = op_input.receive(self.input_name_image)

      print("In-memory image received shape: ", numpy_image.shape)

      # If it's a single channel image, remove the batch dimension (if present)
      if numpy_image.ndim == 3 and numpy_image.shape[0] == 1:
          numpy_image = numpy_image.squeeze(0)

      print("Pil image is: ",numpy_image)

      # Perform inference using the wrapped model
      with torch.no_grad():
          prediction,raw_out = predict(self.ptmodel,numpy_image)  # Calls the predictor function
      print(f"======  this is model raw output: {raw_out}")

      # Check the shape of the prediction
      print(f"Prediction shape: {prediction.shape}")

      # prediction = prediction.squeeze(0)  # Remove batch dimension if it's present
      prediction_norm =  cv2.normalize(prediction,None,0,255,cv2.NORM_MINMAX, cv2.CV_8U)
      cv2.imwrite("/content/DCM2PNG/test.png",prediction_norm)

      op_output.emit(prediction, self.output_name_seg)
      op_output.emit(self.output_folder, self.output_name_saved_images_folder)





## PNGConverterOperator

In [ ]:
# Copyright 2021-2023 MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from os import getcwd, makedirs
from os.path import join
from pathlib import Path
from typing import Union

import numpy as np

from monai.deploy.core import Fragment, Image, Operator, OperatorSpec
from monai.deploy.operators.dicom_data_loader_operator import DICOMDataLoaderOperator
from monai.deploy.operators.dicom_series_to_volume_operator import DICOMSeriesToVolumeOperator
from monai.deploy.utils.importutil import optional_import

PILImage, _ = optional_import("PIL", name="Image")


# @md.env(pip_packages=["Pillow >= 8.0.0", "numpy"])
class PNGConverterOperator(Operator):
    """
    This operator writes out a 3D Volumetric Image to to a file folder in a slice by slice manner.

    Named input:
        image: Image object or numpy ndarray

    Named output:
        None

    File output:
        Generated PNG image file(s) saved in the provided output folder.
    """

    # The default output folder for saving the generated DICOM instance file.
    DEFAULT_OUTPUT_FOLDER = Path(getcwd()) / "output/saved_images_folder"

    def __init__(
        self,
        fragment: Fragment,
        *args,
        output_folder: Union[str, Path],
        **kwargs,
    ):
        print("########  PNG Converter Operator   ########")

        self.output_folder = output_folder if output_folder else PNGConverterOperator.DEFAULT_OUTPUT_FOLDER
        self.input_name_image = "image"
        # Need to call the base class constructor last
        super().__init__(fragment, *args, **kwargs)

    def setup(self, spec: OperatorSpec):
        spec.input(self.input_name_image)

    def compute(self, op_input, op_output, context):
        input_image = op_input.receive(self.input_name_image)
        self.output_folder.mkdir(parents=True, exist_ok=True)
        self.convert_and_save(input_image, self.output_folder)

    def convert_and_save(self, image, path):
        """
        extracts the slices in originally acquired direction (often axial)
        and saves them in PNG format slice by slice in the specified directory
        """
        print("########  PNG Converter Operator   ########")
        rgb_image = None
        if isinstance(image, Image):
            image_data = image.asnumpy()
            pil_image = PILImage.fromarray(image_data)
            if pil_image.mode != "RGB":
              rgb_image = pil_image.convert("RGB")
        elif isinstance(image, np.ndarray):
            image_data = image
            pil_image = PILImage.fromarray(image_data)
            if pil_image.mode != "RGB":
              rgb_image = pil_image.convert("RGB")
        else:
            raise ValueError(f"Input is not Image or ndarray, {type(image)}.")
        image_shape = image_data.shape

        num_images = image_shape[0]

        # for i in range(0, num_images):
        #     input_data = image_data[i, :, :]
        #     pil_image = PILImage.fromarray(input_data)
        #     if pil_image.mode != "RGB":
        #         pil_image = pil_image.convert("RGB")
        rgb_image.save(join(str(path),"model_out_image.png"))




## MaskGenerationPostprocess

In [ ]:
class MaskGenerationPostprocess (Operator):
  def __init__(
        self,
        fragment: Fragment,
        *args,
        app_context: AppContext,
        **kwargs,
  ):
        self.input_name_image = "model_out_image"
        self.output_name_seg = "mask"
        super().__init__(fragment, *args, **kwargs)

  def setup(self, spec: OperatorSpec):
      spec.input(self.input_name_image)
      spec.output(self.output_name_seg)

  def segmentation_map(self,prediction, threshold):
      seg_map = prediction.copy()
      seg_map[seg_map < threshold] = 0
      seg_map[seg_map > 0] = 1
      return seg_map * 255

  def compute(self, op_input, op_output, context):
      import torch
      import numpy as np
      from torchvision.transforms import ToPILImage

      print("=====  Mask Generation Postprocess =====")
      # Receive the image object (assuming it's in monai.deploy.core.domain.image.Image format)
      numpy_mask: Image = op_input.receive(self.input_name_image)
      if len(numpy_mask.shape) > 1:
        print("Mask shape is : ", numpy_mask.shape)
        # If it's a single channel image, remove the batch dimension (if present)
      if numpy_mask.ndim == 3 and numpy_mask.shape[0] == 1:
            numpy_mask = numpy_mask.squeeze(0)

      sm = self.segmentation_map(numpy_mask,0.5)

      sh = numpy_mask.shape
      if isinstance(sh, tuple):
        sh = sh[1]

      new_w = numpy_mask.shape[1] - sh

      # Add black pixels to the right side of the segmentation map
      sm = np.pad(sm, ((0, 0), (0, new_w)), mode='constant', constant_values=0)

      original_size = (numpy_mask.shape[1], numpy_mask.shape[0])
      sm_resized = cv2.resize(sm, original_size, interpolation=cv2.INTER_NEAREST)

      print(f"left sum is {numpy_mask[:,:10].sum()} and right sum is {numpy_mask[:,-10:-1].sum()}")
      if numpy_mask[:,:10].sum() < numpy_mask[:,-10:-1].sum():
          # right side image
          print(" ######## Rotatttteeeeee")
          tmp_mask = np.flip(sm_resized,1)
      else:
          tmp_mask = sm_resized
      cv2.imwrite("mask.png",tmp_mask)
      op_output.emit(sm_resized,self.output_name_seg)







#App.py

#### app

In [ ]:
from pydicom.sr.codedict import codes  # Required for setting SegmentDescription attributes.
from monai.deploy.conditions import CountCondition
from monai.deploy.core import AppContext, Application
from monai.deploy.operators.dicom_data_loader_operator import DICOMDataLoaderOperator
from monai.deploy.operators.dicom_seg_writer_operator import DICOMSegmentationWriterOperator, SegmentDescription
from monai.deploy.operators.dicom_series_selector_operator import DICOMSeriesSelectorOperator
from monai.deploy.operators.dicom_series_to_volume_operator import DICOMSeriesToVolumeOperator
from monai.deploy.operators.stl_conversion_operator import STLConversionOperator
from monai.deploy.operators.dicom_text_sr_writer_operator import DICOMTextSRWriterOperator, EquipmentInfo, ModelInfo

In [ ]:
class VIDA_mask_generation_APP(Application):
    def compose(self):
        print("==== start running app ======")
        app_context = Application.init_app_context({})  # Do not pass argv in Jupyter Notebook
        app_input_path = Path(app_context.input_path)
        app_output_path = Path(app_context.output_path)
        model_path = Path(app_context.model_path)
        self._logger = logging.getLogger("{}.{}".format(__name__, type(self).__name__))
        load_dcm_op = VIDAReadDcmOperator(self, CountCondition(self, 1), input_folder=app_input_path, name="VIDA DICOM LOADER")
        segmentation_op = VIDAoperator(
            self, app_context=app_context, output_folder=app_output_path, model_path=model_path, name="VIDA MASK GENERATION")

        numpy2png = PNGConverterOperator(self,output_folder= app_output_path,name="numpy2png")
        img2mask = MaskGenerationPostprocess(self,app_context=app_context,name = "img2mask")

        self.add_flow(load_dcm_op, segmentation_op, {("image", "image")})
        self.add_flow(segmentation_op,img2mask,{("seg_image","model_out_image")})
        # self.add_flow(segmentation_op,numpy2png,{("seg_image","image")})
        self.add_flow(img2mask,numpy2png,{("mask","image")})

        #############################################
        # Sample_Rules_Text = """
        # {
        #     "selections": [
        #         {
        #             "name": "calcification",
        #             "conditions": {
        #                 "Modality": "MG",
        #                 "ImageType": ["DERIVED", "SECONDARY"],
        #                 "PhotometricInterpretation": "MONOCHROME2",
        #                 "PresentationIntentType": "FOR PRESENTATION"
        #             }
        #         }
        #     ]
        # }
        # """


        # study_loader_op = DICOMDataLoaderOperator(
        #     self, CountCondition(self, 1), input_folder=app_input_path, name="dcm_loader_op"
        # )
        # series_selector_op = DICOMSeriesSelectorOperator(self, rules=Sample_Rules_Text, name="series_selector_op")
        # series_to_vol_op = DICOMSeriesToVolumeOperator(self, name="series_to_vol_op")

        # self.add_flow(study_loader_op, series_selector_op, {("dicom_study_list", "dicom_study_list")})
        # # print(f"Loaded DICOM studies: {study_loader_op}")
        # self.add_flow(
        #     series_selector_op, series_to_vol_op, {("study_selected_series_list", "study_selected_series_list")}
        # )
        # self.add_flow(series_to_vol_op, segmentation_op, {("image", "image")})

        #  ###########################################

        # _algorithm_name = "segmentation of the calcification from breast mammogram"
        # _algorithm_family = codes.DCM.ArtificialIntelligence
        # _algorithm_version = "0.1.0"

        # segment_descriptions = [
        #     SegmentDescription(
        #         segment_label="calcification",
        #         segmented_property_category=codes.SCT.Organ,
        #         segmented_property_type=codes.SCT.Liver,
        #         algorithm_name=_algorithm_name,
        #         algorithm_family=_algorithm_family,
        #         algorithm_version=_algorithm_version,
        #     )
        # ]

        # dicom_seg_writer = DICOMSegmentationWriterOperator(
        #     self, segment_descriptions=segment_descriptions, output_folder=app_output_path, name="dcm_seg_writer_op"
        # )

        # self.add_flow(load_dcm_op, segmentation_op, {("image", "image")})
        # self.add_flow(
        #     load_dcm_op, dicom_seg_writer, {("study_selected_series_list", "study_selected_series_list")}
        # )
        # self.add_flow(segmentation_op, dicom_seg_writer, {("seg_image", "seg_image")})
        self._logger.debug(f"End {self.compose.__name__}")
        print("==== end running app ======")




#### run

In [ ]:
# !rm -rf $HOLOSCAN_OUTPUT_PATH
app = VIDA_mask_generation_APP()
app.run()

[2025-04-01 11:33:42,643] [INFO] (root) - Parsed args: Namespace(log_level=None, input=None, output=None, model=None, workdir=None, argv=[])
[2025-04-01 11:33:42,645] [INFO] (root) - AppContext object: AppContext(input_path=input, output_path=output, model_path=models, workdir=)


==== start running app ======
======  getting the model  =======
########  PNG Converter Operator   ########
==== end running app ======
#######  converting DICOM to numpy array  #######
 the input path is /content/input/data8
image shape before preprocess:  (3328, 2560, 3)
#### load mamm ####
#### preprocess mamm ####
#### left mamm ####
#### clean mamm ####
#### get_act_width ####
#### cut mamm #### (3328, 1682)
#######  DICOM converted  ########
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
===== Passing image to the model =====
In-memory image received shape:  (3328, 1682)
Pil image is:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
model output:  [[ -57.994125  -105.92749   -165.34912   ...   -5.882905    -5.0926633
    -4.1485577]
 [-105.88146   -175.1029    -256

In [ ]:
!python --version


Python 3.11.11


In [ ]:
!unzip -o "/content/drive/MyDrive/Dataset/ai_spleen_seg_bundle_data.zip"

Archive:  /content/drive/MyDrive/Dataset/ai_spleen_seg_bundle_data.zip
  inflating: dcm/1-001.dcm           
  inflating: dcm/1-002.dcm           
  inflating: dcm/1-003.dcm           
  inflating: dcm/1-004.dcm           
  inflating: dcm/1-005.dcm           
  inflating: dcm/1-006.dcm           
  inflating: dcm/1-007.dcm           
  inflating: dcm/1-008.dcm           
  inflating: dcm/1-009.dcm           
  inflating: dcm/1-010.dcm           
  inflating: dcm/1-011.dcm           
  inflating: dcm/1-012.dcm           
  inflating: dcm/1-013.dcm           
  inflating: dcm/1-014.dcm           
  inflating: dcm/1-015.dcm           
  inflating: dcm/1-016.dcm           
  inflating: dcm/1-017.dcm           
  inflating: dcm/1-018.dcm           
  inflating: dcm/1-019.dcm           
  inflating: dcm/1-020.dcm           
  inflating: dcm/1-021.dcm           
  inflating: dcm/1-022.dcm           
  inflating: dcm/1-023.dcm           
  inflating: dcm/1-024.dcm           
  inflating: dcm/